name: CI for Flask App

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl enable docker
        sudo systemctl start docker

    - name: Build Docker image
      run: |
        docker build -t devops-container .

    - name: Run basic tests
      run: |
        echo "Test"

    - name: Run Flask app inside Docker container
      run: |
        docker run -d -p 5000:5000 devops-container
