name: CI for Flask App

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t test1 .

    - name: Run Trivy scan
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy image --format json --output trivy-report.json test1
  
    - name: Upload Trivy report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.json

    - name: Run basic tests
      run: |
        echo "Test"

    - name: Run Flask app inside Docker container
      run: |
        docker run -d -p 5000:5000 test1

    - name: Stop Docker container
      run: |
        docker ps -q --filter "ancestor=test1" | xargs docker stop
